Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/xenial64"
  config.vm.hostname = "{{ item.name }}-{{ item.vm }}"

  config.vm.provider "virtualbox" do |vb|
        #vb.customize ["modifyvm", :id, "--nic1", "bridged"]
        #vb.customize ["modifyvm", :id, "--bridgeadapter1", "eno1"]
  end

  config.vm.network "private_network", ip: "{{ item.ip }}"
#	config.vm.network "public_network", bridge: "eno1"
	config.vm.network "forwarded_port", guest: 22, host: "{{ item.ssh }}"
	config.vm.network "forwarded_port", guest: 80, host: "{{ item.http }}"
	config.vm.network "forwarded_port", guest: 443, host: "{{ item.https }}"

	config.vm.provision "ansible" do |ansible|
		ansible.verbose = "v"
		ansible.playbook = "provision_vm.yml"
		ansible.extra_vars = { ansible_python_interpreter:"/usr/bin/python3" }
	end

end

